Double refactoring
TheDiVaZo/MessageOverHead pull request #2
Opened 2022-02-24 17:20 UTC by TheDiVaZo

Провел рефакторинг остальных классов. 

Изменил классы BubbleMessage и  Bubble. Сделал по правилам конвенции Java.
Изменил названия методов, переменных.
Убрал тот ужас с бесконечными while и заменил одним методом.
Успешно скомпилировал с помощью сборщика Grable и проверил работоспособность с 1.14 по 1.17.

2022-02-24 18:24 UTC, BrainRTP requested changes
Мне очень понравились твои изменения, которые ты внес. Особенно я рад, что ты не пренебрег советом по поводу commit message. Я прочитал его и понял чем ты занимался. Молодец! 👍

Я посмотрел код, на первый беглый взгляд нашел недочеты, дал комментарий по ним. 
Теперь, ты можешь внести изменения в эту же ветку. То бишь, тебе не нужно создавать новую ветку и делать коммит. Просто внеси изменения в эту же ветку и запуш изменения.

2022-02-24 18:24 UTC, BrainRTP commented on bubblemessage/build.gradle
> +    //compileOnly 'org.spigotmc:spigot:1.13-R0.2-SNAPSHOT'
комментарии нужно удалять

2022-02-24 18:24 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/Bubble.java
> +        if (version.contains("1.17")) {
А вот тут лучше использовать систему:  
```
if() {}
else if(){}
else if(){}
```
Т.к  сейчас, если версия == 1.17 и зашли в условие (то бишь, на этой строчке == true условие), то последующие условия будут исполнены. А на это тратится лишнее время.

В конструкции, которую я написал выше, если сработает какое-нибудь условие - последующие условия (в контексте блока if-elseIf) не будут исполнены. Если не понял мое объяснение, лучше обратить к гуглу для прочтения информации о конструкции else if.

2022-02-24 18:24 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/Bubble.java
> +        if (!version.contains("1.15") && !version.contains("1.16") && !version.contains("1.17") && !version.contains("1.18")) {
Выглядит некрасиво. Возможно, стоит преобразовать version в какой-нибудь float и сделать что-то вроде `if (version <= 1.15F) {} else {}`. Но я не уверен будет ли корректно отрабатывать этот функционал.

2022-02-24 18:24 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/BubbleMessage.java
> +    public BubbleMessage(String message, Location loc, JavaPlugin plugin) {
1) Почему `JavaPlugin`, а не просто `Plugin`?
2) Т.к ты ниже присваиваешь переменную, то ты можешь вместо параметра `JavaPlugin plugin` передавать сам класс Main: `Main plugin` (например). Попробуй.

2022-02-24 18:24 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/BubbleMessage.java
> +    List<Bubble> bubbleMessages = new ArrayList<>();
Когда ты инициализируешь переменную, в твоем случае инициализация: `= new ArrayList`
ты можешь установить `final` для переменной. Наверное, IDEA тебе об этом тоже говорила, но ты пропустил это.
При этом, если бы это была просто переменная, по типу `private final String a = "a"`, то ты бы не смог изменить ее. С массивами история немного другая.

2022-02-24 18:24 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/BubbleMessage.java
> +    List<Bubble> bubbleMessages = new ArrayList<>();
Ты тут не указал модификатор доступа переменной (public, private и т.д).
1) Значит, что у тебя тут стоит? 
2) А тебе этот модификатор подходит для данных переменных?

2022-02-24 18:24 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/Main.java
>      public static String makeColors(String s) {
Молодец :)

2022-02-24 18:24 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/Main.java
>  public class Main extends JavaPlugin implements Listener {
А зачем ты используешь `implements Listener`, если в этом классе нет никаких методов "прослушки"? Он тут излишен.
Ты же вынес слушатели в отдельный класс => имплементацию нужно удалить от сюда.

2022-02-24 18:24 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/listener/Listeners.java
> +                        bubbleMessage.spawn(onlinePlayer);
Думаю, что стоит перенести проверку пермишена в начало цикла. Если у пользователя нет прав, то нам и нет смысла расчитывать дистанцию, проводить другие проверки и т.д.

2022-02-25 10:18 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/listener/Listeners.java
> +                        bubbleMessage.spawn(onlinePlayer);
Действительно, ты прав

2022-02-25 10:18 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/Main.java
>  public class Main extends JavaPlugin implements Listener {
Забыл убрать, буду более внимательным

2022-02-27 15:41 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/Main.java
> +        if (Bukkit.getPluginManager().getPlugin("ProtocolLib") == null) {
Это же не имеет смысла, когда у тебя есть `@Dependency("ProtocolLib")` на #28 строчке.
Если плагин ProtocolLib не будет установлен => и сам плагин не будет работать.
Или я ошибаюсь? Ты проверял?

2022-02-27 15:41 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/Main.java
>      public static String makeColors(String s) {
Что такое `s`? Названия переменных должны иметь смысл. Исключения только какие-нибудь дефолтные `for(i...)` и `catch (Exception e)`.

2022-02-27 15:41 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/ReloadConfig.java
>          ((Main) this.plugin).saveParam();
Выглядит странно. Не проще ли было в конструктор передать `Main.class`, а потом его вызвать?
Ты передаешь JavaPlugin, исправь на Main, а дальше без каста класса (присвоение переменной типа класса. Например:
```java
double myDouble = 1.1;
int myInt = (int) myDouble;
```

2022-02-28 07:09 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/Main.java
> +        if (Bukkit.getPluginManager().getPlugin("ProtocolLib") == null) {
Нет, но я все равно сделал на всякий случай :D

2022-03-01 09:46 UTC, merged