Develop UPDATE #2.4
TheDiVaZo/MessageOverHead pull request #6
Opened 2022-03-07 16:33 UTC by TheDiVaZo

[RU]:
Что собственно добавлено:
1. Самообнавляющийся конфиг! Если вышла новая версия, вы просто скачиваете ее и запускаете сервер, а конфигурация уже сама дополняется новыми полями, не убирая старые!
2. Добавлена поддержка невидимости! Если игрок находится под зельем невидимости, либо использует /vanish то над ним не будут отображатся голограммы. Поддерживает SuperVanish
3. Немного оптимизированно появление голограмм
4. Добавлена поддержка метрики
5. Если вышла новая версия плагина, то вы сразу при запуске сервера увидете об этом напоминание!

Все проверил, вроде все работает!

[EN]:
What is actually added:
1. Self-updating config! If a new version is released, you simply download it and start the server, and the configuration itself is supplemented with new fields, without removing the old ones!
2. Added support for invisibility! If the player is under an invisibility potion, or uses /vanish, no holograms will be displayed above them. Supports SuperVanish
3. Slightly optimized appearance of holograms
4. Added support for metrics
5. If a new version of the plugin has been released, you will immediately see a reminder about this when the server starts!

I checked everything, everything seems to work!

2022-03-07 16:40 UTC, TheDiVaZo reviewed
Вот так вот. Пишите если надйете баги

2022-03-07 18:18 UTC, BrainRTP requested changes
Мне понравилась проделанная тобою работа. Жду ответ на каждый комментарий с вопросом. 
Также непонятным остался `/config.yml`. В чем его отличие от `bubblemessage/src/main/resources/config.yml` ?

2022-03-07 18:18 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/Main.java
> +            Bukkit.getLogger().warning("PLEASE, UPDATE MESSAGE OVER HEAR! LINK: https://www.spigotmc.org/resources/messageoverhead-pop-up-messages-above-your-head-1-13-1-18.100051/");
Что это???? 🤔
Если ты хочешь несколько раз вывести сообщение, то пользуйся циклом, а не дублированием кода. 
p.s понятное дело, что если повторений 1-2, то, возможно, и нет смысла пользоваться циклом, но тут явно нужен цикл.

2022-03-07 18:18 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/Main.java
> +            return response.toString();
Почему все завернуто в try? 
Это не есть ошибка, просто интересно. Например, можно 143 и 144 вынести из try-catch.

2022-03-07 18:18 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/Main.java
> +                permissionFormat.put(Integer.parseInt(priority), permFormat);
Объясни словами что тут происходит, пожалуйста, я не понимаю.

2022-03-07 18:18 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/Main.java
> +            message = message.replace(color, "" + ChatColor.of(color.replace("&", "")));
Конструкция слишком сложная. Ты можешь сделать Util-класс, например, `Color.class` с методом а-ля `public static String of(String text...)` который будет это все делать. 
В таком случае, у тебя будет единый формат, например, `Color.of(<String>)`, который будет возвращать уже отформатированную строчку. 
Вот пример: https://github.com/DevCloudMc/EasterEggs/blob/develop/src/main/java/ru/brainrtp/eastereggs/util/text/Colors.java

2022-03-07 18:18 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/Main.java
> +            connectionDefaultConfig.setRequestProperty("User-Agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; .NET CLR 1.0.3705; .NET CLR 1.1.4322; .NET CLR 1.2.30703)");
Думаю, что это излишне. Никак нельзя обойтись без этих параметров?

2022-03-07 18:18 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/listener/Listeners.java
> +                if(onlinePlayer.getWorld().equals(loc.getWorld()) && onlinePlayer.canSee(player) && canSeeSuperVanish(onlinePlayer, player) && !player.hasPotionEffect(PotionEffectType.INVISIBILITY))
Вот это не есть хорошо. Я бы вынес это все в отдельные звучные переменные на строчку выше, а после внутри `if` их бы указал. Читабельность вырастет, i think...

2022-03-07 18:18 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/listener/Listeners.java
>                          if (plugin.isVisibleTextForOwner || !onlinePlayer.equals(player)) {
`!onlinePlayer.equals(player)` это когда-нибудь сработает? 
В каком случае тут будет `false`? 
Я просто думаю о том, что это излишне.

Если игрок написал, значит он в сети, разве не так...

2022-03-07 18:18 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/listener/Listeners.java
> +        int[] priorityFormat = Main.permissionFormat.keySet().stream().mapToInt(x->x).toArray();
Вот это мне тоже объясни, пожалуйста, не понимаю.

2022-03-07 18:18 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/metrics/Metrics.java
> +public class Metrics {
А обязательно этот класс было добавлять в исходники? 
Есть ли возможность импортировать зависимость и работать с этим как с API? 
То бишь, чтобы это было не в пакете плагина, а отдельно, как и происходит со всеми другими зависимостями, которые ты имплиментишь в плагин.

2022-03-07 18:18 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/utils/Bubble.java
> +    private final static int paramArmorStandIndex;
Статика обязательно здесь нужна?

2022-03-08 05:00 UTC, TheDiVaZo commented on bubblemessage/build.gradle
>              // полный путь, куда тебе нужно. У меня вот так:
Понял, удалю

2022-03-08 05:01 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/Main.java
> +@ApiVersion(value=ApiVersion.Target.v1_13)
Да, он прикольный хаха

2022-03-08 05:05 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/Main.java
> +                map.put("Other", entry);
Код скопировал с другого плагина, но, я так понял, версия может быть ю1.x.y (1.14.2) а case-switch вроде сравнивает строки, а не есть ли подстрока в строке

2022-03-08 05:11 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/listener/Listeners.java
>                          if (plugin.isVisibleTextForOwner || !onlinePlayer.equals(player)) {
- Будет false если OnlinePlayer = player. Ведь там мы получаем всех online игроков, и игрок, который написал сообщение, соответсвенно тоже online. А в конфиге есть условие, чтобы игрок, напавший сове сообщение, видел/невидел его над своей головой (другие игроки будут видеть его сообщение над его головой независимо от того, видит ли сам игрок свое сообщение над головой).

2022-03-08 05:14 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/listener/Listeners.java
> +        int[] priorityFormat = Main.permissionFormat.keySet().stream().mapToInt(x->x).toArray();
Тут мы получаем из  permissionFormat приоритеты форматов, и преобразовываем их из Integer в int . А почему x->x то мне idea сказал что x->x.intValue() и x->x тут одно и тоже

2022-03-08 05:15 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/metrics/Metrics.java
> +public class Metrics {
А я пытался его в плагин как зависимость установить, но там все на мавневском и у меня ничего не получилось :( Поэтому решил импортировать его вот таким образом

2022-03-08 05:16 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/utils/Bubble.java
> +    private final static int paramArmorStandIndex;
Это я сделал на будущее, чтобы получать из других классов параметры из Bubble для арморстендов для protocolLib

2022-03-08 05:19 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/listener/Listeners.java
> +                if(onlinePlayer.getWorld().equals(loc.getWorld()) && onlinePlayer.canSee(player) && canSeeSuperVanish(onlinePlayer, player) && !player.hasPotionEffect(PotionEffectType.INVISIBILITY))
Я тогда там каждое условие снесу на отдельную строчку

2022-03-08 05:28 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/Main.java
> +                permissionFormat.put(Integer.parseInt(priority), permFormat);
Сначала мы получаем приоритеты форматов.
Потом создаем переменную permFormat который будет содержать в ячейке [0] - Permisiions ("moh.vip") а в ячейку [1] - сам формат ("&cVIP &f%message%")

Собственно, потом ячейке [1] присвается формат
Но так как у приоритета формата может и не быть поля perm (что значит, что этот формат по умолчанию) то он сначала проверяет, есть ли у него это поле,  и если есть, присваевает ячейке [0] строку с permision, иначе там null

Собственно потом в hashMap'у permissionFormat добавляется приоритет формата и массив данных с форматом

2022-03-08 05:30 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/Main.java
> +            connectionDefaultConfig.setRequestProperty("User-Agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; .NET CLR 1.0.3705; .NET CLR 1.1.4322; .NET CLR 1.2.30703)");
Ну можно объеденить 1 и 2 строчку в одну, но в туториале как делать get запросы на сайты через java было написан такой код :D

2022-03-08 05:30 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/Main.java
> +            return response.toString();
Ну чтоб если тут ошибка была, то он сразу "моя хата с краю ничего не знаю". Хорошо, первые 2 строчки вынесу.

2022-03-08 05:30 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/Main.java
> +            Bukkit.getLogger().warning("PLEASE, UPDATE MESSAGE OVER HEAR! LINK: https://www.spigotmc.org/resources/messageoverhead-pop-up-messages-above-your-head-1-13-1-18.100051/");
Хорошо, хаха

2022-03-08 05:31 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/Main.java
> +    public static final Pattern HEXPAT = Pattern.compile("&#[a-fA-F0-9]{6}");
Пасиба

2022-03-08 05:32 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/Main.java
> +    public static HashMap<Integer, String[]> permissionFormat = new HashMap<Integer, String[]>();
1. сделаю final
2. хз
3. потому что это приоритет формата
4. потому что тут параметры формата, их кстати всего 2. в [0] - permission а в [1]- сам формат

2022-03-08 05:34 UTC, TheDiVaZo commented
> Мне понравилась проделанная тобою работа. Жду ответ на каждый комментарий с вопросом. Также непонятным остался `/config.yml`. В чем его отличие от `bubblemessage/src/main/resources/config.yml` ?

В том что config yml - там чисто конфиг с параметрами, чтобы плагин смог сверится, а resources/config.yml - конфиг который будет в самом плагине.

2022-03-08 05:41 UTC, TheDiVaZo commented on bubblemessage/src/main/java/thedivazo/Main.java
> +            message = message.replace(color, "" + ChatColor.of(color.replace("&", "")));
Хорошо, тогда так и сделаю

2022-03-10 11:20 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/Main.java
> +    public static HashMap<Integer, String[]> permissionFormat = new HashMap<Integer, String[]>();
> 1. сделаю final
> 2. потому что если через plugin.permissionFormat не заработает. А через статику работает хаха!
> 3. потому что это приоритет формата
> 4. потому что тут параметры формата, их кстати всего 2. в [0] - permission а в [1]- сам формат

2 - singletone - плохая практика. Точнее, не всегда уместна. Тут можно обойтись без синглтона.

2022-03-10 11:22 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/Main.java
> +            connectionDefaultConfig.setRequestProperty("User-Agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; .NET CLR 1.0.3705; .NET CLR 1.1.4322; .NET CLR 1.2.30703)");
> Ну можно объеденить 1 и 2 строчку в одну, но в туториале как делать get запросы на сайты через java было написан такой код :D

Если я не ошибаюсь, эти параметры излишне. Найти другой материал по этой теме.

2022-03-10 11:24 UTC, BrainRTP commented
> В том что config yml - там чисто конфиг с параметрами, чтобы плагин смог сверится, а resources/config.yml - конфиг который будет в самом плагине.

Это явно лишнее. Почему нельзя сразу сверять с `resources/config.yml`?

2022-03-11 09:44 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/config/Config.java
>      // Аналогично isParticleEnable
Комментарии остались.

2022-03-11 09:44 UTC, BrainRTP commented on bubblemessage/src/main/java/thedivazo/config/Config.java
> +                plugin.saveConfig();
Тут можно воспользоваться `this.saveConfig();` т.к `plugin == this` но это не точно ;)

2022-03-11 15:57 UTC, merged